# Generated by Django 3.0.2 on 2020-01-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feels_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
